name: Auto Unzip Files

on:
  push:
    paths:
      - '**.zip'   # triggers only when a .zip file is added or changed
  workflow_dispatch:   # allows manual trigger from GitHub Actions tab

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install unzip utility (just in case)
      - name: Install unzip
        run: sudo apt-get install -y unzip

      # Step 3: Find and unzip all .zip files
      - name: Unzip all zip files
        run: |
          mkdir -p unzipped
          for file in $(find . -name "*.zip"); do
            echo "Unzipping $file..."
            unzip -o "$file" -d "./unzipped/$(basename "$file" .zip)"
          done

      # Optional Step 4: Commit and push unzipped contents back
      - name: Commit and push extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add unzipped/*
          git commit -m "Auto-unzipped files from workflow" || echo "No changes to commit"
          git push
